// LAST GAME IS dungeons and degenerate gamble
let files = [
  "1",
"100 Rooms of Enemies",
"10 Bullets",
"10 Minutes Till Dawn",
"10 More Bullets",
"12 Mini Battles",
"13 Bones",
"1 on 1 Soccer",
"1v1.LOL",
"1v1 Tennis",
"2048",
"2048 Cupcakes",
"20 Small Mazes",
"2-3-4 Player Game",
"2Doom",
"2D Shooting",
"3Dash",
"3Dash Editor",
"3D Pinball Space Cadet",
"3 Pandas",
"3 Pandas Brazil",
"3 Pandas Fantasy",
"3 Pandas Japan",
"3 Pandas Night",
"3 Slices 2",
"40x Escape",
"4th and Goal",
"500 Caliber Contractz",
"60 Seconds Burger Run",
"60 Seconds Santa Run",
"64 in 1 NES",
"8 Ball Classic",
"8 Ball Pool",
"9007199254740992",
"90 in 1 NES",
"99 Balls",
"99 Nights ITF",
"A Walk in The Forest (v10)",
"Abandoned 3",
"Absolute Madness",
"Ace Combat 2",
"Ace Combat 3",
"Ace Gangster Taxi",
"Achievement Unlocked",
"Achievement Unlocked (2)",
"Achievement Unlocked 2",
"Achievement Unlocked 3",
"A Chillies",
"A Chillies 2",
"Acko's Mach Bike Challenge (v10)",
"A Dark Room",
"A Date with Death",
"A Day in The Office",
"ADOFAI",
"Advance Wars",
"Advance Wars 2",
"Advance Wars Dual Strike",
"Advent Neon",
"Adventure Capitalist",
"Adventure Capitalist (2)",
"A Flac",
"After the Week",
"Agario Lite",
"Age of War",
"Age of War 2",
"Ages of Conflict",
"Ages of Empire",
"Ahoy Survival",
"A I",
"Airline Tycoon Idle",
"A Koopa's Revenge",
"A Koopa's Revenge 2",
"Akuma no Orgaiden",
"Aladdin SNES",
"Alex Kidd in Miracle World",
"Alien Hominid",
"Alien Hominid GBA",
"Alien Sky Invasion",
"Alien Transporter",
"Alien vs Predator",
"All Bosses in 1",
"Allocation",
"Altered Beast",
"A Maze",
"Ambulance! A Rush",
"Amidst the Sky",
"Amigo Pancho",
"Amigo Pancho 2",
"Amigo Pancho 3",
"Amigo Pancho 4",
"Amigo Pancho 5",
"Amigo Pancho 6",
"Amigo Pancho 7",
"Among Us",
"Amorphous",
"Ancient Sins",
"Anemones Fall",
"Angry Birds Space",
"Angry Birds Space (2)",
"Angry Birds",
"Angry Birds Showdown",
"Angry Birds Space (3)",
"Animal Crossing Wild World",
"Animal Forest N64",
"Ann SSMB",
"Another World",
"Antart Tycoon",
"Anti Matter Dimensions",
"Apes vs Helium",
"A Potris",
"Apple Shooter",
"Apple Worm",
"Aqua Park.io",
"Arceus Legend",
"Archery World Tour",
"Arch Espeelago",
"Arena",
"Armor Mayhem 2",
"Arson Ate",
"Arthur's Nightmare",
"Ascent",
"As Duty Demands",
"A Small World Cup",
"Assessment Examination Que",
"Assessment Examination",
"Asteroids",
"Asteroids ALT",
"Asteroids Arcade",
"Astros Dreamland",
"Astynax",
"Ataria Adventure",
"Attack Hole",
"Avalanche",
"Avia Masters",
"Avia Masters Buggy",
"Awesome Pirates",
"Awesome Planes",
"Awesome Tanks",
"Awesome Tanks 2",
"AX Battler",
"Axis Football League",
"B3313",
"3313 Unabandoned A2",
"3313 v10.2",
"Babel Tower",
"Baby Chic Co Adventure",
"Baby Kaizo",
"Baby Sniper in Vietnam",
"Backrooms",
"Backrooms 2D",
"Backyard Baseball",
"Backyard Baseball 09",
"Backyard Baseball 10",
"Backyard Football",
"Backyard Soccer",
"Bacon May Die",
"Bad Bodyguards",
"Bad Ice Cream",
"Bad Ice Cream 2",
"Bad Ice Cream 3",
"Bad Monday Simulator",
"Bad Parenting",
"Bad Piggies",
"Bad Piggies Latest",
"Bad Time Sim",
"Bad Time Simulator",
"Balatrography",
"Baldi Case OH",
"Baldi Decomp",
"Baldi Epstein",
"Baldi's Basics",
"Baldi's Basics Remaster",
"Baldi's Fun New School Ultimate",
"Ball Blast",
"Ballistic",
"Balls and Bricks",
"Balls and Bricks Good",
"Ballz",
"Banana Simulator",
"Banbuds",
"Bandit Gunslingers",
"Banjo-Kazooie",
"Banjo-Tooie",
"Bank Robbery",
"Bank Breakout 2",
"Bank Robbery 2",
"Barry Has a Secret",
"Bart Blast",
"BAS",
"Baseball Bros",
"Basketball FRVR",
"Basketball Legends (1)",
"Basketball Legends",
"Basketball Stars",
"Basketball Superstars",
"Basket Battle",
"Basket Bros",
"Basket Random",
"Basket Random Good",
"Basket Slam Dunk 2",
"Batter Up",
"Battle Karts",
"Battles",
"Battle Sim",
"Battle Zone",
"Bazooka Boy",
"B Ball Legend",
"Beach Boxing Sim",
"Beam Rider",
"Bearbarians",
"Bear Sus",
"Bejeweled Twist DS",
"Bejeweled Twist Flash",
"Ben 10 Alien Force",
"Ben 10 Omniverse",
"Ben 10 Protector",
"Ben 10 Racing",
"Ben 10 Ultimate Alien",
"Ben Drowned",
"Bergen Truck 201x",
"BFDIA 5b",
"BFDI Branches",
"Big Flappy Tower Tiny Square",
"Big Ice Tower Tiny Square",
"Big Neon Tower Tiny Square",
"Big Shot Boxing 2",
"Big Tower Tiny Square",
"Big Tower Tiny Square 2",
"Big Tower Tiny Square 2 Good",
"Big Time Butter Baron",
"Binding of Isaac's Sheep Time",
"Biohazard 4",
"Bitlife",
"Bitlife Encrypted",
"Bit Planes",
"Blackjack",
"Blackjack Battle",
"Blackjack HHHH",
"Black Knight",
"Blackout",
"Blacksmith Lab",
"Blast Ronaut",
"Blaze Drifter",
"Bleach vs Naruto",
"Blightborne",
"Blobs Story 2",
"Block Blast",
"Block Blast v2",
"Block Craft Parkour",
"Block Craft Shooter",
"Block Post",
"Block the Pig",
"Blocky Demolition Derby",
"Blocky Snakes",
"Blood",
"Blood Money",
"Blood Tournament",
"Bloons",
"Bloons 2",
"Bloons PP 1",
"Bloons PP 2",
"Bloons PP 3",
"Bloons PP 4",
"Bloons PP 5",
"Bloons TD 1",
"Bloons TD 2",
"Bloons TD 3",
"Bloons TD 4",
"Bloons TD 5",
"Bloons TD 6 Scratch",
"Bloxorz",
"Blumgi Racers",
"Blumgi Rocket",
"BMX 2",
"BNTTS",
"Boba Simulator",
"Bob the Robber",
"Bob the Robber 2",
"Bob the Robber 5",
"Bolly Beat",
"Bomberman",
"Bomberman 2",
"Bomberman Hero",
"Bomberman World",
"Bonanza Bros",
"Bonkers SNES",
"Boom Slingers",
"Bottle Cracks",
"Bottle Flip 3D",
"Bot WDS",
"Bounce Back",
"Bounce Masters",
"Bouncy Basketball",
"Bouncy Motors",
"Bounty of One",
"Bowl ALT",
"Bow Master",
"Boxhead 2 Play Rooms",
"Boxhead Nightmare",
"Boxing Live 2",
"Boxing Live 2 (2)",
"Boxing Random",
"Brain Rot",
"Brawl Simulator 3D",
"Brawl Stars",
"Bread Skate",
"Bridge Race",
"Brotato",
"BTD 1",
"BTD 5",
"BTTS",
"BTTS 2",
"Bubble Shooter",
"Bubble Shooter Pirate",
"Bubble Tanks",
"Bubble Tanks 2",
"Bubble Tanks 3",
"Bubble Tanks Arenas",
"Bubble Tanks TD",
"Bubsy",
"Buckshot Roulette",
"BuildNow GG",
"Bullet Force",
"Bunny Land",
"Bunzo Bunny",
"Burger and Frights",
"Burger Time",
"Burrito Bison",
"Burrito Bison 2",
"Burrito Bison Launch Alibre",
"Burrito Bison Revenge",
"Bushido Blade",
"Buster Jam",
"Cactus McCoy (1)",
"Cactus McCoy",
"Cactus McCoy 2 (1)",
"Cactus McCoy 2 (2)",
"Cactus McCoy 2",
"Call of Battle",
"Camilla",
"Candy Box 1",
"Cannon Balls 3D",
"Cannon Fodder",
"Captain Lang",
"Captcha Ware",
"Capybara Clicker",
"Car Crash 3",
"Card Drawing",
"Car Eats Car 2 Deluxe",
"Carking Arena",
"Car Mods",
"Car Ramp vs Police Chase",
"Car Stunts Driving",
"Cartoon Network Table Tennis Ultimate Tournament",
"Cast Away",
"Castlevania Bloodline",
"Castlevania Circle of the Moon",
"Castlevania",
"Castlevania 2",
"Castlevania 3",
"Castlevania Aria of Sorrow",
"Castlevania Dawn of Sorrow",
"Castlevania NES",
"Castle Wars Modern",
"Cat Mario",
"Cat Mario Good",
"Cats Love Cake 2",
"Cave Crawler",
"Cave Story",
"Celeste",
"Celeste 2",
"Celeste Mario DX",
"Celia's Stupid ROM Hack",
"Cell Door",
"Cell to Singularity",
"Centipede Arcade",
"Chain of Memories",
"Chaos Faction 2",
"Checkers",
"Cheese Chompers 3D",
"Cheese Is the Reason",
"Cheese Rolling",
"Cheshire in a Chatroom",
"Chess",
"Chess Classic",
"Chibi Knight",
"Chicken CS",
"Chicken Scream",
"Chicken War",
"Chips Challenge",
"Choppy Orc",
"Choroq Wonderful",
"Chrono Trigger",
"Chuzzle",
"Circlo O2",
"Civi Balls",
"Civi Balls 2",
"Clash 'n' Slash",
"Clash of Vikings",
"Class of 09",
"Claymore",
"Clay Uncraft",
"Clean Up IO",
"Clear Vision",
"Clear Vision 2",
"Clear Vision 3",
"Clear Vision 4",
"Clear Vision 5",
"Climb for Brain Rots",
"CL Madness Ambulation",
"Clover",
"Club by the Seal",
"Cluster Rush",
"Coal LLC Demo",
"Call of Duty 4",
"Call of Duty Black Ops",
"Call of Duty Defiance",
"Code Name Gordon",
"Code.org",
"Code.org But Offline",
"Coder Craft",
"Call of Duty Modern Warfare",
"Call of Duty World at War",
"Coffee Maker",
"Cold Pines",
"Color Burst 3D",
"Color Match",
"Color Water Sort 3D",
"Combo Pool",
"Command and Conquer",
"Commander Keen 4",
"Commander Keen 5",
"Commander Keen 6",
"Confronting Urself",
"Confronting Yourself",
"Conker's Bad Fur Day",
"Contra",
"Contra 3",
"Cookie Clicker",
"Cookie Clicker (2)",
"Cookie Clicker Cool",
"Cookie Clicker Good",
"Cookie Clicker Mod Menu",
"Cooking Mama",
"Cooking Mama 2",
"Cooking Mama 3",
"Core Ball",
"Cory in the House",
"Circle of the Lion King",
"Count Masters Stick Man Games",
"Cover Orange",
"Cover Orange 2",
"Cover Orange Journey Gangsters",
"Cover Orange Journey Knights",
"Cover Orange Journey Pirates",
"Cover Orange Journey Space",
"Cover Orange Players Pack",
"Cover Orange Players Pack 2",
"Cover Orange Players Pack 3 (1)",
"Cover Orange Players Pack 3",
"Crank It!",
"Crank It",
"Crash 2",
"Crash 3",
"Crash Bandicoot (1)",
"Crash Bandicoot",
"Crash Bandicoot 2",
"Crash Team Racing",
"Crazy Cars",
"Crazy Cattle 3D",
"Crazy Chicken 3D",
"Crazy Climber",
"Crazy Frog Racer",
"Crazy Motorcycle",
"Crazy Penguin Catapult",
"Crazy Plane Landing",
"Crazy Taxi GBA",
"Creature Card Idle",
"Creeper World 2",
"Creepy Internet Stories",
"Creepy Night Funkin",
"Crimson Madness",
"Crossy Road",
"Crunch Ball 3000",
"Crystal Castles",
"Counter Strike 1.6",
"Counter Strike",
"Counter Strike DS",
"CS GO Clicker",
"CTG P Nitro",
"Curve Ball (1)",
"Curve Ball",
"Customer Support",
"Cut the Rope",
"Cut the Rope Holiday",
"Cut the Rope Time Travel",
"CVOOC",
"Cyberbun Racing",
"Cyber Sensation",
"Dad Game",
"Dadish",
"Dad & Me",
"Daggerfall",
"Dandy's World Clicker",
"Dank Tomb",
"Dash Arena",
"Dash.io",
"Dashmetry",
"Date with Iraq",
"DB Origins",
"DB Origins 2",
"DB Sniper",
"DBZ Attack Saiyans",
"DBZ Devolution",
"DBZ Super Warriors Sonic",
"DBZ Warriors 2",
"DDL C64",
"Dead Air",
"Dead Estate",
"Dead Frontier Outbreak",
"Dead Frontier Outbreak 2",
"Deadly Descent",
"Dead Plate",
"Dead Seat",
"Dead Zed",
"Dead Zed 2",
"Death Chase",
"Death Run",
"De Blob 2",
"Decision",
"Decision 2",
"Decision 3",
"Decision Medieval",
"Deeper Sleep",
"Deepest Sword",
"Deep Sleep",
"Defender Arcade",
"Defend Your Castle",
"Defend Your Nuts",
"Defend Your Nuts 2",
"Deltarune",
"Delta Traveler",
"Dementium",
"Demolition Derby Crash Racing",
"Demon Blade",
"Demon Bluff",
"Diablo",
"Diamond Hollow",
"Diamond Hollow 2",
"Diddy Kong Racing",
"Die in the Dungeon",
"Dig Deep",
"Dig Dug",
"Dig Dug 2",
"Dig Dug 2.6",
"Dig to China",
"Dimensional Incident",
"Dino Dudes",
"Dino Run",
"Dino Run Enter Planet D",
"Dino Run Marathon of Doom",
"Dire Decks",
"DKC Competition Cart",
"DK NES Collection (1)",
"DK NES Collection",
"Doblox",
"Doge Miner",
"Doge Miner 2",
"Doki Doki Literature Club",
"Dome Romantik",
"Donkey Kong",
"Donkey Kong 64",
"Donkey Kong 94",
"Donkey Kong Country",
"Donkey Kong Country 2",
"Donkey Kong Country 3",
"Donkey Kong NES",
"Don't Escape",
"Don't Escape 2",
"Don't Escape 3",
"Don't You Lecture Me",
"Doodle Jump",
"Doodle Jump Goober",
"Doom",
"Doom 2",
"Doom 2D",
"Doom 2D DOS",
"Doom 2 DOS",
"Doom 3 Pack",
"Doom 64",
"Doom DOS",
"Doom Emscripten",
"Doom PS",
"Doom PS Alt",
"Doom Zio",
"Doors Castle",
"DOS Wasm X",
"Double Dribble",
"Douchebag Life",
"Douchebag Workout",
"Douchebag Workout 2",
"Down the Mountain",
"Dragon Ball Advance",
"Dragon Ball Z - The Legacy of Goku",
"Dragon Quest 5 DS",
"Dragon Quest IX",
"Dragon Warrior Monsters",
"Dragon x Client",
"Draw Climber",
"Drawn to Life",
"Drawn to Life 2",
"Draw the Line",
"D Reader",
"Dread Head Parkour",
"Drift Boss",
"Drift Hunters Merge",
"Drift Simulator",
"Drive Mady",
"Driven Wild",
"Driver Russia",
"Dr Mario",
"Dr Weed Gaster",
"DTA 6",
"Dubstep",
"Duck Hunt",
"Duck Life 5",
"Duck Life",
"Duck Life 2",
"Duck Life 3",
"Duck Life 4",
"Duck Life Battle",
"Duck Life Space",
"Ducklings.io",
"Duck Tales",
"Duck Tales 2",
"DUD",
"Duke Nukem 2",
"Duke Nukem 3D",
"Dumb Ways to Die",
"Dumpling",
"Dune Buggy",
"Dungeon Deck",
"Dungeon Raid",
"Dungeons and Degenerate Gamblers",
"Dunk Shot",
"Dusk Child",
"Dying Dreams",
"Dynamite Headdy",
"Eaglercraft Alpha 126 Offline",
"Eaglercraft Beta 1.3 Offline",
"Eaglercraft Beta 13 Offline",
"Eaglercraft Indev Offline (1)",
"Eaglercraft Indev Offline (1) (2)",
"Eaglercraft Indev Offline (2)",
"Eaglercraft Indev Offline",
"Eaglercraft 1.5.2",
"Eaglercraft L 19 v0.7.0 Offline Signed (1)",
"Eaglercraft L 19 v0.7.0 Offline Signed",
"Eaglercraft Nebula",
"Eagle Ride",
"Learn to Die",
"Learn to Die 2",
"Earthbound",
"Earthbound 3",
"Earthbound SNES",
"Earth Taken",
"Earth Taken 2",
"Earth Taken 3",
"Earthworm.gg",
"Earthworm Jim (1)",
"Earthworm Jim",
"Earthworm Jim 2 (1)",
"Earthworm Jim 2",
"Edelweiss",
"Eddy's Car Simulator",
"Effing Hail",
"Effing Machines",
"Effing Worms",
"Effing Zombies",
"Egg",
"Eggy Car",
"Elastic Face",
"Electric Man 2",
"Elevator Action",
"Elytraflight",
"Emujs",
"Enchain",
"Endacopia",
"Endless War 4",
"Endless War 5",
"Endless War 5 WOW",
"Endless War 7",
"Enduro",
"Epic Battle Fantasy 5",
"Escalating Duel",
"EscapeRoad",
"EscapeRoadCity2",
"EscapeSchoolDuel",
"E.T.",
"E.TrianosOdyssey",
"EurovisionSim",
"EvilGlitch",
"E.Volution",
"ExciteBike64",
"ExitPath",
"EXOObservation",
"ExtremeRun3D",
"FactoryBalls",
"FactoryBalls2",
"FactoryBalls3",
"FactoryBalls4",
"FairyTalevsOnePiece",
"FallGuys",
"Fallout",
"Famidash",
"Famidash1.2.8",
"FamidashAlbum1.2.8",
"FamidashB-Sides1.2.8",
"FamidashC-Sides1.2.8",
"FamidashD-Sides1.2.8",
"FamilyGuyCorrupted",
"FancyPantsAdventure",
"FancyPantsAdventure2",
"FancyPantsAdventure3",
"FancySnowboarding",
"FantasyZone",
"FashionBattle",
"FattyGenius",
"FearAssessment",
"FearstoFathom-HomeAlone",
"FeedtheVoid",
"FeedUs",
"FeedUs2",
"FeedUs3",
"FeedUs4",
"FeedUs5",
"FinalFantasyII-TheWaroftheLion",
"FF 3",
"FinalFantasyVI",
"FridayNightFunkin-A.F.S",
"FinalFantasy-MysticQuest",
"FF Sonic 1",
"FF Sonic 2",
"FF Sonic 3",
"FF Sonic 4",
"FF Sonic 5",
"FF Sonic 61",
"FF Sonic 62",
"FIFA 07",
"FIFA 10",
"FIFA 11",
"FIFA 2000 (1)",
"FIFA 2000 (2)",
"FIFA2000",
"FIFA 99",
"FIFA International Soccer",
"FIFA Road to World Cup 98",
"FIFA Soccer 06",
"FIFA Soccer 95",
"FIFA Soccer 96",
"FIFA Soccer 97",
"FIFA Street 2",
"FinalEarth2",
"FinalFantasy",
"FinalFantasy2NES",
"FinalFantasy3NES",
"FinalFantasyII",
"FinalFantasyIX",
"FinalFantasyLegend2",
"FinalFantasyTactics",
"FinalFantasyVI (2)",
"FinalFantasyVII",
"FinalFantasyVIID-2",
"FinalFantasyVIID-3",
"FinalFantasyVII-TheOtherTetrr",
"FinalNinja",
"FindtheAlien",
"FireBlob",
"FireboyandWatergirl",
"FireboyandWatergirl2",
"FireboyandWatergirl3",
"FireboyandWatergirl5",
"FireboyandWatergirl6",
"FireEmblem",
"FishEat-GettingBig",
"Fisquarium",
"FiveNightsatBaldi'sRedone",
"FiveNightsatEpstein's",
"FiveNightsatShrek's",
"FiveNightsatShrek'sHotel",
"FiveNightsatYoshi's",
"FlappyBird",
"FlashSonic",
"FloodRunner",
"FloodRunner2",
"FloodRunner4",
"Fluidism",
"FNAc1",
"FNAc2",
"Five Nights at Freddy's",
"Five Nights at Freddy's 2",
"Five Nights at Freddy's 3",
"FNAF3Remastered",
"Five Nights at Freddy's 4",
"FNAF4Halloween",
"FNAFAnimatronics",
"FNAFPS",
"FNAFShooter",
"FNAFSL",
"FNAFUCN",
"FNAFWorldD",
"FNaW",
"FNF-Aethos",
"FNF-Agoti",
"FNF-Akage",
"FNF-Animation",
"FNF-Annie",
"FNF-ASDF",
"FNF-BelowDepths",
"FNF-BFDI26",
"FNF-BinaryBreakdown",
"FNF-BlackBetrayal",
"FNF-B-Side",
"FNF-Camellia'sRudeBlaster",
"FNF-CandyCarrier",
"FNF-Chara",
"FNF-CityTales",
"FNF-Classified",
"FNF-Corrosion",
"FNF-Cory",
"FNF-Crunchin",
"FNF-Deciever",
"FNF-Desolation",
"FNF-DocumicTxtV3",
"FNF-DokiTakeoverPlus",
"FNF-DropandRoll",
"FNF-D-Sides",
"FNF-Dustin",
"FNF-DustTale",
"FNF-Fleetway",
"FNF-FlippedOut",
"FNF-FNAF1",
"FNF-FNAF2",
"FNF-FNAF3",
"FNF-FNAFPT",
"FNF-GameBreakerBundle",
"FNF-GFMode",
"FNF-Godot",
"FNF-GoldenApple",
"FNF-Hank",
"FNF-HeartbreakHavoc",
"FNF-Herobrine",
"FNF-Hex",
"FNF-Holiday",
"FNF-HorkGlorpGloop",
"FNF-Hotline",
"FNF-Hypno'sLullaby",
"FNF-Imposter3",
"FNF-ImposterV4",
"FNF-IndieCross",
"FNF-InfernalBout",
"FNF-InfiniteIrida",
"FNF-IronLung",
"FNF-JapCreepyPasta",
"FNF-MadnessPoop",
"FNF-MaginaGeMatches",
"FNF-MarioMadnessD-Side",
"FNF-MarioPort",
"FNF-MCMadness",
"FNF-Midfight",
"FNF-Miku",
"FNF-MobMod",
"FNF-Neo",
"FNF-PiggyField",
"FNF-Plutoshi",
"FNF-PokePastaPerdition",
"FNF-Porifera",
"FNF-QT",
"FNF-Remnants",
"FNF-Retrospecter",
"FNF-RevMixed",
"FNF-Rewrite",
"FNF-RhythmicRev",
"FNF-RottenSmoothie",
"FNF-SelfPaced",
"FNF-Shaggy4Keys",
"FNF-ShaggyXMatt",
"FNF-Shucksv2",
"FNF-ShucksV2",
"FNF-Sky",
"FNF-Soft",
"FNF-Sonic.exe",
"FNF-Sonic.exe4",
"FNF-StarlightMayhem",
"FNF-StridentCrisis",
"FNF-TailsGetsTrolled",
"FNF-TooSlowFran",
"FNF-Tricky",
"FNF-TWIDDLEFINGER",
"FNF-Undertale",
"FNF-Void",
"FNF-VSTabi",
"FNF-WaltenFiles",
"FNF-WednesdayInfidelity",
"FNF-Whitty",
"FNF-Zardy",
"Focus",
"FolderDungeon",
"FootballBros",
"FootballLegends",
"ForknSausage",
"FortZone",
"FPA4P1",
"FPA4P2",
"FreeGemas",
"FreeRider",
"FreeRider2",
"FreeRider3",
"FridayNightFunkin",
"FroggerArcade",
"FromRusttoAsh",
"FruitNinja",
"FunkinMix",
"FunnyBattle",
"FunnyBattle2",
"FunnyMadRacing",
"FunnyShooter2",
"FunnyShooter2.2",
"FuschiaX",
"Fused240",
"F-Zero",
"F-ZeroX",
"GachaVerse",
"Gain Ground",
"Galaga",
"GameandWatchCollection",
"GameWatchGallery3",
"GangstaBean",
"GangstaBean2",
"GangsterBros",
"Garcello",
"Garfield-CaughtinAct",
"GDLite",
"GeneralChaos",
"GenericFighterMaybe",
"GeometryDashScratch",
"GeometryVibes",
"GeorgeandthePrinter",
"GetAwayShootout",
"GetonTop",
"Get to the Top Although There is No Top",
"GetYoked",
"GunstarHeroesShinobi",
"GunstarHeroesShinobi2",
"GhostTrick",
"GimmetheAirpod",
"GladdiHoppers",
"GLFighters",
"GloryHunters",
"G-Lover",
"GoalsSouthAfrica",
"Gobble",
"GoingBalls",
"GoldDiggerFRVR",
"GoldenAxe",
"GoldenAxe2",
"GoldenAxe3",
"GoldenEye007",
"GoldenSun",
"GoldenSunNDS",
"Golden Sun - The Lost Age",
"GoldMiner",
"GolfBattle",
"GolfOrbit",
"GolfSunday",
"GoodBigTowerTinySquare",
"GoodBigTowerTinySquare2",
"GoodBoyGalaxy",
"GoodMonkeyMart",
"GoofTroopsNES",
"GoogleBaseball",
"GoogleDino",
"GoreScriptClassic",
"GorillaTag",
"GotoBed",
"GrandActionSimulator-NY",
"GrandDad",
"GrandEscapePrison",
"GrandTheftAutoAdvance",
"Granny",
"Granny2",
"Granny2.2",
"Granny3",
"GrannyCreepy",
"Granny Nightmare",
"Granny Y",
"Gran Turismo",
"Gran Turismo 2",
"Grass Mowing",
"Gravity",
"Gravity Mod",
"Greener Grass Awaits",
"Grey-Box Testing",
"Grimace Birthday",
"Grind Craft",
"Grn",
"Grow a Garden",
"Grow Denio",
"Grow Mi",
"Grow Your Garden",
"GTA",
"GTA 2",
"GTA 2.2",
"GTA 2 Alt",
"GTA Alt",
"GTA Alty",
"GTA China",
"GTA Mods",
"Guess Their Answer",
"Gun Spin",
"Gun Blood",
"Guncho",
"Gun Fighter Jesse James",
"Gun Knight",
"Gun Mayhem",
"Gun Mayhem 2",
"Gun Mayhem 2 Goof",
"Gun Mayhem Redux",
"Gun Night",
"Gun Smoke",
"Gunstar Heroes",
"Gym Stack",
"Gyromite",
"Hacx",
"Hajime Ippo",
"Hajime no Ippo",
"Half-Life",
"Halo Combat Devolved",
"Handshakes",
"Hands of War (1) (2)",
"Hands of War (1)",
"Hands of War (2)",
"Hands of War",
"Handulum",
"Hanger",
"Hanger 2",
"Hang On SMS",
"Happy Room",
"Happy Wheels",
"Hardware Tycoon",
"Harmony of Dissonance",
"Harold's Bad Day",
"Harvest.io",
"Harvest Moon",
"Harvest Moon 2",
"Harvest Moon 64",
"Haunted School",
"Haunt the House",
"Heart and Soul",
"Heart and Soul 1.2.1 (2)",
"Heist",
"Helios Offline (1)",
"Helios Offline",
"Helix Jump",
"Hell Ron",
"Help, No Brakes",
"Heretic",
"Hero 3 Flying Robot",
"Herobrine Reborn",
"Hextris",
"High Speed",
"High Stakes",
"Highway Racer 2",
"Highway Traffic 3D",
"Hill Climb Racing Lite",
"Hi No Homo",
"Hipster Kickball",
"Hit 8 Ox",
"Hit Single Real",
"Hit Stun Fly",
"HL2 Doom",
"Hobo",
"Hobo 2",
"Hobo 3",
"Hobo 4",
"Hobo 5",
"Hobo 6",
"Hobo 7",
"Hobo vs Zombies",
"Hoenn's Last Wish",
"Hole Battle",
"Hole.io",
"Hollow Knight",
"Home Sheep Home",
"Horror Mickey Mouse",
"Hot Dog Bush",
"Hot Wax",
"House of Hazards",
"Hover Racer Drive",
"Huggy Wuggy Pixel",
"Human Expenditure Program",
"Hungry Knight",
"Hungry Lamu",
"Hyper Sandbox",
"I Can't Believe Google Flagged Me for the Name of the File LOL",
"Ice Age Baby",
"Ice Dodo",
"Ice Fishing",
"Icy Purple Head",
"Idle Breakout",
"Idle Dice",
"Idle Football Manager",
"Idle Idle Game Dev",
"Idle Miner Tycoon",
"Idle Minor Zamn Shes 1.2",
"Impossible Quiz (1)",
"Impossible Quiz",
"Impossible Quiz 2",
"Inclement Emerald",
"Indian Trucks Simulator",
"Infinite Craft",
"Ink Game",
"Inkwell (v104)",
"Innkeeper",
"Inside Story",
"Insomniary",
"Intellisphere",
"Interactive Buddy",
"Linto Ruins",
"Into Space",
"Into Space 2",
"Into Space 3",
"Into the Deep Web",
"Intrusion",
"IQ Ball",
"Iron Snout",
"Iron Soldier",
"Irori",
"It Gets So Lonely Here",
"I Wanna Be the Guy",
"Jacksmith",
"Jacksmith Encrypted or Smthn",
"Jailbreak Obbbobob",
"James Bond Jr",
"Jazz Jackrabbit",
"Jazz Jackrabbit 2",
"Jefflings",
"Jelly Dad Hero",
"Jelly Drift",
"Jelly Mario",
"Jelly Truck",
"Jelly Truck Good",
"Jet Force Gemini",
"Jetpack Joyride",
"Jet Rush",
"Jet Ski Racing",
"J Mocraft",
"Johnny Trigger",
"Johnny Upgrade",
"Jojo Baps 1",
"Journey Arcade",
"Journey Downhill",
"Joust Arcade",
"JS Vecx",
"Jumbo Mario",
"JUMP",
"Jumping Shell",
"Jungle Book SNES",
"Jungle Deer Hunting",
"Jurassic Park",
"Just Fall LOL",
"Just Hit the Button",
"Just One Boss",
"Kaizo Mario World",
"Kalikan",
"Kanye Zone",
"Kapi",
"Karate Bros",
"Karlson",
"Kart Bros",
"Ken Griffey Jr. Presents Major League Baseball",
"Kerosene Client",
"Killer Instinct",
"Kill Over",
"Kill the Ice Age Baby Adventure",
"Kim Jong Un Tile Puzzle",
"Kingdom Hearts Days",
"Kingdom Hearts Recoded",
"Kingdom Hearts Recoded Alt",
"Kirby 64",
"Kirby 64 Crystal Shards",
"Kirby and the Amazing Mirror",
"Kirby Canvas Curse",
"Kirby's Adventure",
"Kirby's Dream Land",
"Kirby's Dream Land 3",
"Kirby Soft and Wet",
"Kirby Squeak Squad",
"Kirby Super Star",
"Kirby Super Star Ultra",
"Kirby Tilt and Tumble",
"Kitten Cannon",
"Klifur",
"Knife Hit",
"Nightmare Tower",
"Knock Knock",
"Konk Rio",
"Koopa's Revenge",
"Kou Rio",
"KS2 Teams",
"Lacey's Flash Games",
"Last Fire Red",
"Last Horizon",
"Last Stand",
"Last Stand 2",
"Leader Strike",
"Leap and Avoid 2",
"Learn to Fly",
"Learn to Fly 2",
"Learn to Fly 3",
"Learn to Fly 3 Debug",
"Learn to Fly Idle",
"Learn to Fly Idle Hack",
"Legacy of Goku",
"LEGO Batman",
"LEGO Batman 2 Superheroes",
"LEGO Indiana Jones",
"LEGO Indiana Jones 2",
"LEGO Ninjago",
"LEGO Star Wars",
"LEGO Star Wars 2 GBA",
"LEGO Star Wars GBA",
"Lemmings",
"Let It Consume",
"Let's Go Eevee",
"Let's Go Pikachu",
"Level Devil",
"Lever Warriors",
"Light It Up",
"Lil Run Mo",
"Lime",
"Line Rider",
"Link's Awakening DX",
"Link to the Past",
"Little Alchemy 2",
"Little Run Mo",
"Lock the Door",
"Lode Runner",
"Lone Wolf",
"Los Angeles Shark",
"Low Knight",
"LOZ 1",
"LOZ Link's Awakening",
"LOZ Minish Cap",
"LOZ Oracle of Seasons",
"LOZ Phantom Hourglass",
"LOZ Spirit Tracks",
"LSE",
"Lucid",
"Lucky Blocks",
"Lumber Obby",
"Lummm",
"Madelin Stunt Cars",
"Madelin Stunt Cars Good",
"Madelin Stunt Cars Multiplayer Fixed",
"Madden 93",
"Madden 94",
"Madden 95",
"Madden 96",
"Madden 99",
"Madden Football",
"Madden Football 64",
"Madden NFL",
"Madden NFL 2000",
"Madden NFL 2001",
"Madden NFL 2002",
"Maddy 98",
"Madness - Retaliation",
"Madness Accelerant",
"Madness Combat Defense",
"Madness Combat Nexus",
"Madness Gemini",
"Madness Hydraulic",
"Madness Interactive",
"Madness Off Color",
"Madness Premeditation",
"Madness Retaliation",
"Madness - 2010",
"Madness Stand",
"Mad Skills Motocross 2",
"Mad Stick",
"Mad Stunt Cars 2",
"Mage Tower Idle",
"Magic Tiles 3",
"Majora's Mask",
"Make Sure it's Closed",
"MAMI",
"Manage a God",
"Marble Racer (2)",
"Marble Racer",
"Mari0",
"Mario Party Advance",
"Mario 3",
"Mario 64 WebGL",
"Mario and Luigi - Super Star Saga",
"Mario Builder 64 (2)",
"Mario Builder 64",
"Mario Combat",
"Mario Golf",
"Mario is Missing Done Right",
"Mario Kart 64",
"Mario Kart DS",
"Mario Kart Super Circuit",
"Mario - The Lost Levels",
"Mario Madness",
"Mario Maker SNES",
"Mario vs. Rabbids",
"Mario Paint",
"Mario Party",
"Mario Party 2",
"Mario Party 3",
"Mario Party DS",
"Mario's Mystery Meat",
"Mario Tennis",
"Mario Tennis GB",
"Mario vs. Luigi",
"Marvel Super Heroes Arcade",
"Marvel vs Capcom PS1",
"Marvel vs Street Fighter",
"Marvel vs. Street Fighter JP",
"Masked Forces Unlimited",
"Mastermind World Conqueror",
"Matrix Rampage",
"Matt v2",
"Maui Mallard",
"Max Payne",
"MCFPSFBHD",
"McRae Rally",
"Meat Boy",
"Meat Boy Flash",
"Medal of Honor",
"Medieval Shark",
"MediEvil",
"Mega CD",
"Mega Chess",
"Mega Client",
"Mega Man",
"Mega Man 2",
"Mega Man 2 GBA",
"Mega Man 3",
"Mega Man 4",
"Mega Man 5",
"Mega Man 5 GB",
"Mega Man 6",
"Mega Man 7",
"Mega Man 8",
"Mega Man Bass CFTF",
"Mega Man Battle Chip Challenge",
"Mega Man BN 5 TC",
"Mega Man BN 5 TP",
"Mega Man BN 6 CF",
"Mega Man BN 6 CG",
"Mega Man Legends",
"Mega Man Legends 2",
"Mega Man X",
"Mega Man X2",
"Mega Man X3",
"Mega Man X4",
"Mega Man X5",
"Mega Man X6",
"Mega Man Zero",
"Mega Man ZX",
"Mega Miner",
"Melon Playground",
"Meow Uwu",
"Merge Round Racers",
"Metal Gear",
"Metal Gear Solid",
"Metal Gear Solid PS",
"Metal Slug",
"Metal Slug 2",
"Metal Slug Advance",
"Metal Slug Mission 1",
"Metal Slug Mission 2",
"Metal Sonic Hyperdrive",
"Metroid",
"Metroid 2",
"Metroid Fusion",
"Metroid Prime Hunters",
"Metroid Zero Mission",
"Miami Shark",
"Mickey Mania SNES",
"Micro Life",
"Micro Mages",
"Midway's Greatest Hits N64",
"Mighty Knight",
"Mighty Knight 2",
"Mimic",
"Minceraft I NotMine V6 (1)",
"Minceraft I NotMine V6",
"Mindscape",
"Mindwave",
"Mine Caves",
"Minecraft 1.8.8",
"Minecraft Case Sim",
"Minecraft Pocket Edition",
"Minecraft Shooter",
"Minecraft Tower Defense",
"Mine Shooter",
"Mine Sweeper Plus",
"Min Hero",
"Mini Crossword",
"Mini Flips",
"Mini Mart",
"Mini Shooters",
"Mini Tooth",
"Miragine War",
"Missile Command",
"MK4 Amped Up",
"MK Mythologies N64",
"MK Trilogy PS1",
"MMBN 3 B",
"MMBN 3 W",
"MMBN 4 BM",
"MMBN 4 RS",
"MMBN WS",
"MMSF2 ZXN",
"MMSF2 ZXS",
"MMSF3 BA",
"MMSF3 RJ",
"MMSF D",
"MMSF L",
"MMSF P",
"MM Wily Wars",
"M O64 (2)",
"M O64",
"Mob Control HTML5",
"Mobius Revolution",
"Moemon Emerald Vanilla+ (v110)",
"Momim Sleeping",
"Momos Crushers",
"Money Rush",
"Monkey Mart",
"Monkey Mart ENC",
"Monster Derby",
"Monster Swing",
"Monster Tracks",
"Monster Truck Curfew",
"Monster Truck Port Stunt",
"Moon Emerald Extreme Randomizer",
"Mortal Kombat",
"Mortal Kombat 2",
"Mortal Kombat 2a",
"Mortal Kombat 3",
"Mortal Kombat 3a",
"Mortal Kombat 4 (2)",
"Mortal Kombata",
"Mortal Kombat Advance",
"Mort Kom 4",
"Motherload",
"Motor Road Rash",
"Moto X3M 2",
"Moto X3M 3",
"Moto X3M M",
"Moto X3M Pool Party",
"Moto X3M Spookyland",
"Moto X3M Winter",
"Mountain Bike Racer",
"Mr. Mine",
"Mr. Racer",
"Ms. Pac-Man (2)",
"Ms. Pac-Man (3)",
"Ms. Pac-Man (4)",
"Ms. Pac-Man",
"Multitask",
"Mutilate a Doll",
"MVP Baseball",
"MX Off Road Master",
"My Friend Pedro",
"My Friend Pedro Arena",
"My Teardrops",
"N",
"NARC",
"Natsuki 64",
"Natural Selection",
"Nautilus OS (1)",
"Nautilus OS",
"NBA Hangtime",
"NBA Jam",
"NBA Jam TE",
"NBA Live 2000",
"NBA Live 2003",
"NBA LOX",
"Neon Blaster",
"Neon Rider",
"NES World Champion",
"Net Attack",
"Never Ending Legacy",
"Newer SMBS DS",
"Newgrounds Rumble",
"New Super Mario Bros",
"New Super Mario World 2 Around the World",
"New York Shark",
"Next Door",
"NFL Blitz",
"NFS Carbon - Own City",
"NFS Most Wanted",
"NFS Porsche Unleashed",
"NFS Underground",
"NFS Underground 2",
"N-GON (2)",
"N-GON",
"NHL 2002",
"NHL 98",
"NHL Hitz 2003",
"Nickelodeon Super Brawl 2",
"Nicktoons Freeze Frame Frenzy",
"Night Cat Survival",
"Night Club Showdown",
"Nightfire",
"Nightshade",
"Nike Hub",
"Nimrods",
"Ninja Brawl",
"Ninja Obby Parkour",
"Nintendogs Lab",
"Nintendo World Cup",
"NIT Client",
"Nitrome Must Die",
"No More Game",
"Noob Miner",
"Not Your Pawn",
"Nova Client",
"N Plus",
"NSMB U DS",
"NSMB W DS",
"Nubby's Number Factory",
"Null Kevin",
"Nuts and Bolts Screwing Puzzle",
"NZP",
"Obby - 99 Will Lose",
"Obby 1 Jump Per Click",
"Obby 456",
"Obby Bike",
"Obby Cart",
"Obby Only Up",
"Obby Rainbow Tower",
"Obby Slide",
"Obby Swing",
"Obby Yard Sale",
"Obey the Game",
"Ocarina of Time",
"Odd Bot Out",
"Odd Future",
"Offline Paradise",
"Oh Flip",
"Omega Layers",
"Omega Nugget Clicker",
"Omnipresent",
"Onebit Adventure",
"Clone Night as Freddy",
"One Piece",
"One Piece Fighting",
"Clone Shot Old",
"Only Up",
"Oot Master Quest",
"Operius",
"Opposite Day",
"Possum Country",
"Orange Roulette",
"Orb of Creation",
"Ordinary Sonic ROM Hack",
"Oregon Trail",
"Origami King",
"Ork, I'm a Stick with It Can Be Remembered, Oh Yeah, Alien Hominid",
"Mortal Kombat 4",
"OSU",
"Purple Guy",
"Out Hold",
"Outnumbered",
"Outrun Arcade",
"Outrun Genesis",
"Over Burden",
"Ovoum",
"Ovo 2",
"Ovo Dimensions",
"Ovo Fixed",
"Pac-Man",
"Pac-Man A",
"Pac-Man Super Fast",
"Pac-Man World 3",
"Pac-Man World G",
"Pac-Man World PSX",
"Panda Meic 2",
"Papa's Bakeria",
"Papa's Donut",
"Papa Louie Night Hunt 2",
"Papa Louie When Burgers Attack",
"Papa Louie When Pizzas Attack",
"Papa Louie When Sundaes Attack",
"Papa's Pizza Good",
"Papa's Pizza Goody",
"Papa's Pizza Mamamia",
"Papa's Burger III Aaaaa",
"Papa's Cheeseria",
"Papa's Cupcakeria",
"Papa's Freezeria",
"Papa's Hot Doggeria",
"Papa's Pancakeria",
"Papa's Pastaria",
"Papa's Scooperia",
"Papa's Sushiria",
"Papa's Tacomia",
"Papa's Wingeria",
"Paperio",
"Paperio 3D",
"Paperio Mania",
"Paper Mario",
"Paper Mario DSE",
"Paper Mario Practice Hack",
"Paper Mario Pro Mode",
"Paper Mario The Thousand-Year Door",
"Parappa the Rapper",
"Parappa the Rapper (Alt)",
"Parking Fury",
"Parking Fury 2",
"Parking Fury 3",
"Parking Rush",
"Partners in Time",
"Peace Keeper",
"Peach",
"Peggle",
"Penalty Kicks",
"Penguin Diner",
"Penguin Pass",
"Pepsiman",
"Pepsiman (Alt)",
"Pereiılous",
"Perfect Dark",
"Perfect Hotel",
"Persona",
"Persona 2",
"Persona 2 (Alt)",
"Persona (Alt)",
"Pet World",
"Phantasy Star",
"Phantasy Star 2",
"Phantasy Star 3",
"Phantasy Star 4",
"Phasma",
"Phoenix Justice for All",
"Phoenix Right Ace Attorney",
"Phoenix Trials and Year",
"Phoenix Trials and Year (Error)",
"Pibby Apocalypse",
"Piclient",
"PICO-8",
"PICO-8 Edu",
"Pico Driller",
"Pico Hot",
"Pico Life",
"Pico Night Punkin",
"Picos School",
"Pico vs Beardx",
"Pieces of Cake",
"Pikwip",
"Ping Pong Chaos",
"Pink Bike",
"Pint",
"Pitfall",
"Pit of 100 Trials",
"Pixel Battlegrounds.io",
"Pixel Combat 2",
"Pixel Gun",
"Pixel Quest Lost Idols",
"Pixel Shooter",
"Pixel Speedrun",
"Pixel Warfare",
"Pizza Papa",
"Pizza Tower",
"PKM Naruto Ans",
"Planet Life",
"Plangman",
"Plants vs Zombies (2)",
"Plants vs Zombies NDS",
"Plazma Burst",
"Plinko",
"Plonky",
"Pogo 3D",
"Poke Academy Life Forever",
"Poke All In",
"Poke Ambrosia",
"Poke Battle Fact",
"Poke Black",
"Poke Black 2 (Alt)",
"Poke Black 2 HTML",
"Poke Black (Alt)",
"Poke Blaze Black 2 Redux",
"Poke Blue",
"Poke Classic",
"Poke Crown",
"Poke Crystal Advance Redux",
"Poke Crystal Clear",
"Poke Diamond",
"Poke Dreamstone",
"Poke Elite Redux",
"Poke Elysiuma",
"Poke Elysiumb",
"Poke Emerald Enhanced",
"Poke Emerald Exceeded",
"Poke Emerald Horizons",
"Poke Emerald Imperium",
"Poke Emerald Random",
"Poke Emerald Rogue",
"Poke Emerald Rogue EX",
"Poke Emerald Z",
"Poke Fire Gold",
"Poke Flora",
"Poke FRLG Plus",
"Poke Fused Dimension",
"Poke Fusion 3",
"Poke Gaia",
"Poke Golden Shield",
"Poke GS Chronicles",
"Poke Heart Gold",
"Poke Heartgold Generations",
"Poke Light Platinum",
"Poke Liquid Crysta",
"Poke Megamoemon",
"Pokemon Amnesia",
"Pokemon Clover",
"Pokemon Crystal",
"Pokemon Emerald",
"Pokemon Emerald Crest",
"Pokemon Emerald Imperium",
"Pokemon Emerald Kaizo",
"Pokemon Emerald Mini",
"Pokemon Emerald Rouge",
"Pokemon Emerald Seaglass",
"Pokemon Energized Emerald",
"Pokemon Evolved (Error)",
"Pokemon Fire Red",
"Pokemon Fire Red and Leaf Green Plus Edition",
"Pokemon Fire Red Randomized",
"Pokemon Gold",
"Pokemon Kaizo Iron Fire Red",
"Pokemon Lazarus",
"Pokemon Leaf Green",
"Pokemon Modern Emerald",
"Pokemon Mystery Dungeon",
"Pokemon Perfect Emerald 55",
"Pokemon Quetzal",
"Pokemon Roaring Red",
"Pokemon Rocket Edition (2)",
"Pokemon Ruby",
"Pokemon Saiph",
"Pokemon Saiph 2",
"Pokemon Sapphire",
"Pokemon Shin Sigma",
"Pokemon Silver",
"Pokemon SL Green",
"Pokemon SM Red",
"Pokemon Snap",
"Pokemon SORS",
"Pokemon SORS 2",
"Pokemon Stadium",
"Pokemon Stadium 2",
"Pokemon Tower Defense",
"Pokemon Ultimate Fusion",
"Pokemon Unbound",
"Pokemon Volume 1",
"Pokemon Volume 2",
"Pokemon Volume 3",
"Pokemon Volume 4",
"Pokemon Emerald (2)",
"Pokemon Galaxy",
"Pokemon Mystery Explorers of Sky",
"Pokemon Nameless",
"Pokemon Odyssey",
"Pokemon Pasta",
"Pokemon Path",
"Pokemon Pearl",
"Pokemon Perfect FireRed",
"Pokemon Pisces",
"Pokemon Platinum",
"Pokemon Platinum Randomized",
"Pokemon Pure Blue",
"Pokemon Pure Green",
"Pokemon Pure Red",
"Pokemon Recharged Pink",
"Pokemon Recharged Yellow",
"Pokemon Record Keepers",
"Pokemon Red",
"Pokemon Renegade Plat",
"Pokemon Rocket Edition",
"Pokemon Rowe",
"Pokemon Ruby (2)",
"Pokemon Run and Bun",
"Pokemon Scorched Silver",
"Pokemon Soul Silver",
"Pokemon Sun Sky",
"Pokemon TCG 1",
"Pokemon TCG 2",
"Pokemon the Pit",
"Poke Theta Emerald EX",
"Pokemon Too Many Types 2",
"Pokemon Tourmaline",
"Pokemon Ultraviolet",
"Pokemon Unova Emerald",
"Pokemon Vega",
"Pokemon Volt White 2 Redux",
"Pokemon Voyager",
"Pokemon White",
"Pokemon White 2",
"Pokemon White 2 Alt",
"Pokemon Yellow",
"Pokemon Emerald Rush Edition (20)",
"Pokemon Trade & Stache (V11)",
"Pokemon TWO (v11)",
"Pokemon Stunning Steel",
"Police Pursuit 2",
"Polished Crystal",
"Polytrack but Not Flagged (1)",
"Polytrack but Not Flagged",
"Polytrack Works Now",
"Pom Gets Internet",
"Poor Bunny",
"Popeye Papi",
"Pork Like",
"Portal",
"Portal 2D",
"Portal Defenders Fastbreak",
"Portal Defenders TD",
"Portal Flash",
"Porter",
"Portrait of Ruin",
"Possess Quest",
"Postal",
"Potato Man Seeks the Roof",
"POU (1)",
"POU",
"Powerslave",
"Praxis Fighter X",
"Pre Bronze Age",
"Pre Civilization Bronze Age",
"Prehistoric Shark",
"Primary",
"Prismarine",
"Processor Tycoon",
"Professor Layton and the Curious Village",
"Puckman",
"Pull Frog",
"Pumpkin Run",
"Punch-Out!!",
"Punch the Drump",
"Punch the Trump",
"Puppet Hockey",
"Puppet Master",
"Push Your Luck",
"Puyo Puyo Fever",
"Plants vs Zombies",
"Plants vs Zombies 2",
"Plants vs Zombies 2 Gardenless",
"PVZ M",
"Pyro Toad",
"Q*bert",
"Q*bert Arcade",
"Q.T.Rewired",
"Quake 2",
"Quake 3",
"Quake 64",
"Quantum Clicker",
"Quickie World",
"QWOP",
"Race Master 3D",
"Racing Arena",
"Radical Red",
"Rad Racer",
"Raft Wars",
"Raft Wars 2",
"Ragdoll.io",
"Ragdoll Achievement",
"Ragdoll Archers",
"Ragdoll Drop",
"Ragdoll Hit",
"Ragdoll Runners",
"Ragdoll Soccer",
"Ragoll Hit",
"Rainbow Six",
"Rainbow Six Alt",
"Ral Disc Crack House",
"Raven Base",
"Ray 1",
"Ray 2",
"Rayman",
"Raze",
"Raze 2",
"Raze 3",
"RE3",
"Reach the Core",
"Real Flight Sim",
"Rebuild",
"Rebuild 2",
"Recoil",
"Red Alert",
"Red Ball",
"Red Ball 2",
"Red Ball 3",
"Red Ball 4 (1)",
"Red Ball 4",
"Red Ball 4 Vol 2",
"Red Ball 4 Vol 3",
"Red Handed",
"Red Tie Runner",
"Red v Blue Fix",
"Red vs Blue 2",
"Red vs Blue War",
"Reign of Centipede",
"Renegades",
"Repo Bad",
"Resident Evil",
"Resident Evil 2",
"Resident Evil 2D 1",
"Resident Evil 2D 2",
"Resizer",
"Resort Empire",
"Retro Bowl",
"Retro Bowl College",
"Retro Highway",
"Retro Ping Pong",
"Return Man",
"Return Man 2",
"Return to Riddle School",
"Revolution Idle",
"Rewrite 2",
"RH",
"Rhythm Heaven",
"Rhythm Heaven (2)",
"Ricochet Kills 2",
"Riddle",
"Riddle Middle School",
"Riddle School",
"Riddle School 2",
"Riddle School 3",
"Riddle School 445544444 444 444 (2)",
"Riddle Transfer",
"Riddle Transfer 2",
"Riddle University Fix",
"Ridge Racer",
"Rise Higher",
"Ristar",
"Road Fighter",
"Road of Fury",
"Road of the Dead",
"Road of the Dead 2",
"Road Runner NES",
"Rocket Goal.io",
"Rocket Jump",
"Rocket Knight 2 (1)",
"Rocket Knight 2 (1) (2)",
"Rocket Knight 2 (2)",
"Rocket Knight 2",
"Rocket Knight Adventures",
"Rocket League",
"Rocket Pult",
"Rocket Soccer Derby",
"Rodha",
"Rogue Soul",
"Rogue Soul 2",
"Roller Baller",
"Rolling Sky",
"Rolly Vortex",
"Roily Poly Monster",
"Rooftop Run",
"Rooftop Snipers",
"Rooftop Snipers 2",
"Room Clicker",
"Rose Gold",
"Rotate",
"Roulette Hero",
"Roulette Knight",
"Ruffle",
"Run 2",
"Run",
"Run 2 (2)",
"Run 3",
"Running Fred",
"Russian Buckshot",
"Russian Car Driver",
"Russian Sandbox",
"SAI Hate Station",
"Sandbox City",
"Sandbox Els",
"Sands of the Coliseum",
"Sandstone (1)",
"Sandstone",
"Sandtris",
"Santa Run",
"Santy",
"SAS Zombie Assault 2",
"Satryn",
"Saul Goodman Run",
"Sausage Flip",
"Sayori's Notebook",
"Scale the Depths",
"Scampton The Great Fight Recreate",
"Scarlet and Violet",
"Scarlet Shift",
"Scary Maze Game",
"Scary Shawarma",
"Scary Teacher 3D",
"Schoolboy Runaway",
"Scrap Metal 3",
"Scrapyard Dog",
"Scratch Options",
"Scribblenauts",
"Scuba Bear",
"SD - The War",
"SDF",
"Sea Mongrel",
"Secret of Mana",
"Sega 2 GG",
"Sega Sonic The Hedgehog",
"Self",
"Sentry Fortress",
"Sereni Trove",
"Serious Sam Advance",
"Serving Up Madness",
"Seven Days",
"SFK",
"SFK 2",
"SFK Last Stand",
"SFK League",
"Shadow Courier",
"Shadow Dancer",
"Shadow Dancer Secret",
"Shaggy (1)",
"Shaggy",
"Shantae GB",
"Shape Transform",
"SHC 1",
"SHC 2",
"SHC 3",
"Shift",
"Shift 2",
"Shift 3",
"Shift at Midnight",
"Shin Megami Tensei Devil Survivor",
"Shinobi",
"Shinobi 3",
"Shinobi Revenge",
"Shopping Cart Hero",
"Short Life",
"Shotout 4",
"Shred Mill",
"Shred Sauce",
"Shrek 2",
"Shrubnaut",
"Shw Ultimatem",
"Side Effects",
"Side Pocket",
"Sierra 7",
"Silent Hill",
"Silent Hill Alt",
"Silk",
"Silk Melody",
"Silo Showdow",
"Silver",
"Sim City 64",
"The Simpsons Arcade",
"SINGLEFILE",
"Six Ways to Die",
"Skate It",
"Skate or Die",
"Skibidi Gyatt",
"Skibidi in the Backrooms",
"Skibidi Shooter",
"Skinwalker",
"S Kong",
"Sky Race 3D",
"Sky Riders",
"Skywire",
"Skywire 2",
"Slenderman",
"Slendy Tubbies",
"Slice It All",
"Slide in the Woods",
"Slime Laboratory",
"Slip Ways",
"Slither.io",
"Slope",
"Slope 2 Player",
"Slope 3",
"Slope Plus",
"Slot or Not",
"Slow Roads",
"SM 63 Redux",
"SM64 Green Stars",
"SM64 Hidden Stars",
"SM64 Land",
"SM64 Last Impact",
"SM64 Liminal Dream",
"SM64 OOT",
"SM64 Sapphire",
"SM Advance 2",
"SM Advance 3",
"Smash Hit Ripoff",
"Smash Karts",
"Smash Karts Working",
"Smash Remix",
"Smash Remix 2.0.1 (2)",
"SMB 1-2",
"SMBC",
"SMB Crossover",
"SMB Game Over",
"SMB Remastered",
"SMC",
"SMGDS",
"Snail Bob",
"Snail Bob 2",
"Snail Bob 3",
"Snail Bob 4 Space",
"Snail Bob 5 Love Story",
"Snake Is",
"Snake Like",
"Sniper Shot",
"Sniper v2",
"Snowball.io",
"Snowboard Obby",
"Snow Bros (1)",
"Snow Bros (1) (2)",
"Snow Bros (2)",
"Snow Bros",
"Snow Bros Genesis",
"Snow Brothers",
"Snow Drift",
"Snow Rid",
"Snow Rideee",
"Snow Rider",
"Snow Rider Goody Gumdrops",
"Snow Riderrrr",
"Snow Road",
"Snow White",
"Soccer Bros",
"Soccer Random",
"Soccer Random Good",
"Soda Simulator",
"Solar Sandbox",
"Solar Smash",
"Solatrobo",
"Solitaire",
"Solstice",
"Somari 64",
"Sonic & Knuckles + Sonic The Hedgehog 3",
"Sonic 1 Contemporary",
"Sonic 1 Mobile",
"Sonic 1 Score Rush",
"Sonic 1 The Super Challenges",
"Sonic 2 Mobile",
"Sonic 2 Pink Edition",
"Sonic 2 Score Rush",
"Sonic 2 Time and Place",
"Sonic 3 and Knuckles",
"Sonic 3 and Sally",
"Sonic 3 Complete",
"Sonic 3D Blast",
"Sonic 3D Blast DX",
"Sonic Advance",
"Sonic Advance 2",
"Sonic Advance 2 SP",
"Sonic Advance 3",
"Sonic and Ashuro",
"Sonic and Falling Star",
"Sonic and Knuckles",
"Sonic Battle",
"Sonic Blast",
"Sonic CD",
"Sonic CD Mobile",
"Sonic Chaos",
"Sonic Classic Collection",
"Sonic Classic Heroes (1)",
"Sonic Classic Heroes",
"Sonic Classics",
"Sonic Colors",
"Sonic Delta Origins",
"Sonic EXE OG",
"Sonic EXE Razor",
"Sonic GG",
"Sonic Hellfire Saga",
"Sonic in SM64",
"Sonic in SMW (1)",
"Sonic INSMW (2)",
"Sonic in SMW",
"Sonic Jam",
"Sonic Labyrinth",
"Sonic Mania",
"Sonic Mania Plus",
"Sonic Mega Mix",
"Sonic Mon",
"Sonic Pocket Adventure",
"Sonic R",
"Sonic RALT",
"Sonic Revert",
"Sonic Rush",
"Sonic Rush Adventure",
"Sonic Scorched Quest",
"Sonic Spinball",
"Sonic the Hedgehog",
"Sonic the Hedgehog 2",
"Sonic the Hedgehog 3",
"Sonny 2",
"Sort the Court",
"SOTN",
"Soul Jumper",
"Soundboard",
"South Park N64",
"Sovereign of the Skys",
"Spacebar Clicker",
"Space Company",
"Space Harriers SMS",
"Space Invade 95",
"Space Invaders",
"Space is Key",
"Space is Key 2",
"Space is Key Xmas",
"Space Wars Battleground",
"Space Waves",
"Special Mission",
"Speed per Click",
"Speed Stars",
"Spelunky",
"Spewer",
"Spiderman PS1",
"Spiral Roll",
"Spirits of Hell",
"Spongebob Power Kart Grand Prix",
"Sports Heads Ice Hockey",
"Sprinter",
"Sprunked",
"Sprunki",
"Sprunki Clicker",
"Spy Hunter",
"Squid Playground",
"SSF2 Arcade",
"SSFT Arcade",
"Stack Ball.io",
"Stack Tris",
"Stacky Dash",
"Star Fox",
"Star Fox 64",
"Star Raiders",
"State.io",
"Station 141",
"Station Meltdown",
"Station Saturn",
"Steak and Jake",
"Steal Brain Rot",
"Steal Brain Rot Online",
"Stealth Assassin",
"Stealth Master",
"Steel Empire",
"Steel Surge",
"Steep Descent",
"Stick Archers Battle",
"Stick Defenders",
"Stick Fighter",
"Stick Jet Challenge",
"Stick Man and Guns",
"Stick Man Clash",
"Stick Man Duel",
"Stick Man GT a City",
"Stick Man Hook",
"Stickman Kingdom Clash",
"Stick Man Kombat 2D",
"Stickman Stealing Diamond",
"Stick Merge",
"Stick Min Air Ship",
"Stick Min Breaking Bank",
"Stick Min Escaping Prison",
"Stick Min Flee Complex",
"Stick RPG Complete",
"Stick Slasher",
"Stick War",
"Stick War 2",
"Stick With It",
"Storm the House",
"Storm the House 2",
"Storm the House 3",
"Strange Journey",
"Stranger Rope Police",
"Street Fighter 1 Arcade",
"Street Fighter II",
"Street Fighter 2 Arcade",
"Street Fighter 2 CE Arcade",
"Street Fighter 2 HF Arcade (1)",
"Street Fighter 2 HF Arcade",
"Street Fighter II Turbo",
"Street Fighter Alpha 3",
"Street Fighter Umuh Something",
"Streets of Rage",
"Streets of Rage 2",
"Streets of Rage 3",
"Strike Force Heroes",
"Strike Force Heroes 2",
"Strike Force Heroes 3",
"Striker Dummies",
"Style Savvy",
"Subway Surfers Barcelona",
"Subway Surfers Beijing",
"Subway Surfers Berlin",
"Subway Surfers Buenos Aires",
"Subway Surfers Havana",
"Subway Surfers Houston",
"Subway Surfers Iceland",
"Subway Surfers London",
"Subway Surfers Mexico",
"Subway Surfers Miami",
"Subway Surfers Monaco",
"Subway Surfers New Orleans",
"Subway Surfers New Orleans (2)",
"Subway Surfers San Francisco (1)",
"Subway Surfers San Francisco",
"Subway Surfers San Francisco (2)",
"Subway Surfers St. Petersburg",
"Subway Surfers Winter Holiday",
"Subway Surfers Zurich",
"Sugar Sugar",
"Suika",
"Suika Pico",
"Summer Rider",
"Sun and Moon",
"Super Bomberman",
"Super Bomberman 2",
"Super Bomberman 3",
"Super Bomberman 4",
"Super Bomberman 5",
"Super C",
"Super Car Rush",
"Super Castlevania VI",
"Super Chibi Knight",
"Super Cold",
"Super Dark Deception",
"Super Diagonal Mario 2",
"Super Drome Bugs",
"Super Drome Bugs (2)",
"Super Falling Fred",
"Super Fighters",
"SUPERHOT",
"Superhot Line Miami",
"Super House of Dead Ninjas",
"Super Island Adventure",
"Super Liquid Soccer",
"Super Mario",
"Super Mario 3 Mix",
"Super Mario 63",
"Super Mario 64",
"Super Mario 64 DS",
"Super Mario 74",
"Super Mario All Stars",
"Super Mario Bros",
"Super Mario Bros 2",
"Super Mario Bros 2 US",
"Super Mario Bros 3",
"Super Mario Bros 3 Real",
"Super Mario Kart",
"Super Mario Land",
"Super Mario Land 2",
"Super Mario Land 2 DX",
"Super Mario Land DX",
"Super Mario Mon",
"Super Mario RPG",
"Super Mario Star Road",
"Super Mario Star Road Retooled",
"Super Mario Sunshine 64",
"Super Mario World",
"Super Mario World 2",
"Super Mario World The Secret of The 7 Golden Statues",
"Super Metroid",
"Super Monkey Ball Jr",
"Super Noah's Ark 3D",
"Super Oliver World",
"Super Onion Boy 2",
"Super Pickleball Adventure",
"Super Punch-Out",
"Super Punch-Out EN",
"Super Puzzle Fighter II Turbo",
"Super Puzzle Fighter II Turbo Alt",
"Super Santa Kicker",
"Super Santa Kicker 2",
"Super Scribblenauts",
"Super Smash Bros",
"Super Smash Flash",
"Super Smash Flash 08",
"Super Smash Flash 2",
"Super Smash Flash 2 But Dif Version",
"Super Street Fighter II Turbo JP",
"Super Tilt Bros",
"Sup IT Dept",
"Supreme Duelist",
"Supreme Duelist 2019",
"Survival Race V2",
"Survivor.io",
"Sushi Cat",
"Sushi Cat 2",
"Sushi Unroll",
"Swerve",
"Switchblade",
"Sword and Shield Ultimate Plus",
"Sword Fight",
"Sword Play",
"Swords and Sandals",
"Swords and Sandals 2",
"Swords and Souls",
"Sydney Shark",
"Tabi",
"Tablet Tanks",
"Table Tennis World Tour",
"Taco Stand",
"Tag",
"Tag C3",
"Tag CM",
"Taiko no Tatsujin",
"Tail of the Dragon",
"Touhou Taisei",
"Takeover",
"Tallio",
"Tall Man Run",
"Tank Mayhem",
"Tank Pixel",
"Tank Trouble",
"Tanuki Sunset",
"Tanuki Sunset Uhhhhhhhh",
"Tapper",
"Tap Road",
"Tasty Planet",
"TBoi Demo",
"TBoi Lamb Eternal",
"Tecmo Bowl",
"Tekken 2 PS1",
"Tekken 3 PS1",
"Telephone Trouble",
"Telocation",
"Tempest 2000",
"Temple of Boom",
"Temple Run 2",
"Tempo Overdose",
"TEOD",
"Terra",
"Territorial.io",
"Territory War",
"Territory War 2",
"Territory War 3",
"Tetris",
"Tetris Attack",
"Tetris GBA",
"Tetris Grand Master 2",
"Thanks for Reminding Me I Had to Fix This",
"The Classroom",
"The Classroom 2",
"The Classroom 3",
"The Dead Seat",
"The Deepest Sleep",
"The Dude",
"The Enchanted Cave 2",
"The Impossible Game",
"The Incredible Machine",
"The Last Stand",
"The Last Stand Union City (1)",
"The Last Stand Union City",
"The Lone Ranger",
"The Man in the Window",
"Theme Park",
"The Pit",
"There Is No File",
"Thermomorph",
"The Sodor Race",
"The Sun For The Vampire",
"They Are Coming",
"This Is the Only Level",
"This Is the Only Level 2",
"This Is the Only Level Too",
"Three Goblets",
"Throw a Potato",
"Throw a Potato Again",
"Thwack",
"Tiberian Dawn",
"Time Shooter 2",
"Time Shooter 3",
"Time Warriors",
"Tiny Fishing",
"TMNT",
"TMNT 2 ARC",
"TMNT ARC",
"TMNT Turtles in Time",
"To a Starling",
"Toaster Ball",
"ToeJam & Earl",
"ToeJam & Earl Panic on Funkotron",
"Tomb of the Mass",
"Tomorrow and Yesterday",
"Tomodachi Collection",
"Tony Hawk's Pro Skater 2",
"Tony Hawk's Pro Skater 4",
"Tony Hawk's Underground",
"Too Many Types",
"Top Speed Racing 3D",
"Toss the Turtle",
"TOTM",
"Touhou",
"Touhou 2",
"Touhou 3",
"Touhou 4",
"Touhou 5",
"Tower Blocks",
"Tower Crash 3D",
"Tower Wizard",
"Townscraper",
"Trace",
"Traffic Jam 3D",
"Tra-La-Lero Tra-La-La Escape Tung Tung Tung Sahur",
"Trapped With Jester",
"Trap the Cat",
"Treachorous Trials",
"Treachorous Trials Part 2",
"Triachnid",
"Triple Play 2000",
"Trivia Crack",
"Troll Face Quest 1",
"Troll Face Quest 10",
"Troll Face Quest 11",
"Troll Face Quest 12",
"Troll Face Quest 13",
"Troll Face Quest 2",
"Troll Face Quest 3",
"Troll Face Quest 4",
"Troll Face Quest 5",
"Troll Face Quest 6",
"Troll Face Quest 7",
"Troll Face Quest 8",
"Troll Face Quest 9",
"Truck Sim",
"Tsuzuki Maze",
"Tube Jumpers",
"Tung Tung Horror",
"Tung Tung Tung Sahur Obby",
"Tunnel Rush",
"Tunnel Rush Better",
"Tuper Tario Tros",
"Turbo Stars",
"Turok Dinosaur Hunter",
"Twinshot (1)",
"Twinshot (1) (2)",
"Twinshot",
"Twisted Metal",
"Twisted Metal 2",
"Two Ball 3D",
"UCDS",
"Ucky Block Obby Euphrates River",
"UFO Swamp Oddyssey",
"Ultima",
"Ultimate Assassin 2",
"Ultimate Assassin 3",
"Ultimate Card Driving Simulator",
"Ultimate Mortal Kombat",
"Ultimate Mortal Kombat 3",
"ULTRAKILL",
"Um Jammer Lammy",
"Um Stick Man Game IDK I Forgor",
"Uncanny Cat Golf",
"Underneath",
"Undertale LB",
"Undertaler",
"Undertale Yellow",
"Unfair Mario",
"Unfair Mario Work Question Mark",
"Unfair Undyne",
"Unicycle Hero",
"Unitres Dreams",
"UNO",
"Unown King",
"Untime",
"Untitled Goose Game",
"Upgrade Complete",
"Upgrade Complete 2",
"Upslash",
"Usterrush",
"UZG",
"Vampire Survivors",
"Vanguard",
"Vapor Trails",
"Vex",
"Vex 2",
"Vex 3",
"Vex 3 Xmas",
"Vex 4",
"Vex 5",
"Vex 6",
"Vex 7",
"Vex 8",
"Vex Challenges",
"Vexx3M",
"Vexx3M 2",
"Villager",
"Vincent Mansion of the Dead",
"Visitor",
"Volley Random",
"Vollyball Challenge",
"Vortex",
"VS Agore",
"VS Nonsense",
"VSSMB",
"VVVVVV (1)",
"VVVVVV",
"Waluigi Taco Stand",
"Warfare 1917",
"Warfare 1944",
"Wario Land 1",
"Wario Land 3",
"Wario Land 4",
"WarioWare DIY",
"WarioWare Inc",
"War the Knight",
"Water Poolio",
"Waterworks",
"Wave Dash",
"Wave Race 64",
"Wave Run",
"We Become What We Behold",
"Web Fishing",
"Weltling",
"Wermhole",
"Whack the Thief",
"Whack Your Boss",
"Whack Your Computer",
"What a Mario World",
"Wheelie Bike",
"Wheely",
"Wheely 2",
"Wheely 3",
"Wheely 4",
"Wheely 5",
"Wheely 6",
"Wheely 7",
"Wheely 8",
"Wily Wars",
"Windows Doors",
"Winter Falling",
"Winter Olympics",
"Wipeout 2097",
"Wipeout 2097 Alt",
"Witchcraft TD",
"Wolf Child",
"Wolfenstein",
"Wolfenstein 3D",
"Woodworm",
"Wordle",
"World Cup 98",
"World's Hardest Game",
"World's Hardest Game 2",
"World's Hardest Game 3",
"World's Hardest Game 4",
"WPN Fire",
"Wrassling",
"Wrestle Bros",
"WWF Attitude",
"WWF SmackDown 2",
"X Event",
"Xevious",
"X-Men Arcade",
"X-Men Children of The Atom Arcade",
"X-Men vs Street Fighter",
"Yandere Simulator",
"Yar's Revenge",
"Yellow",
"Yo Ho Ho Io",
"Yoshi's Strange Quest",
"You Are Lucky",
"Your Turn to Die",
"You vs 100 Skibidi",
"Yume Nikki",
"ZDoom",
"Zelda 2 the Legend of Link",
"Zelda Indigo ch2",
"Zelda Minish Cap",
"Zenword",
"Zoinkz",
"Zombie Exploder",
"Zombie Road",
"Zombie Rush",
"Zombies Ate My Neighbors",
"Zombpocalypse 2",
"Zombotron",
"Zombotron 2",
"Zombotron Reboot",
"Zrist",
"Zuma",
"Zuma Shooter",
"Öoo",
"Baldi's 3",
"Baldi's B",
"100 in 1 NES",
"10 Bullets",
"10 Yard Fight",
"1942 NES",
"Ace Attorney Miles Edgeworth",
"Advance Wars Dual Strike",
"Alex Kidd in Miracle World",
"Angry Birds 2",
"Angry Birds Slingshot Frenzy",
"Animal Crossing",
"Animal Forest N64",
"Antipathy",
"Arcade Volley",
"classroommaxxing",
"3313 Unabandoned A2",
"Bad Ice Cream 2",
"Bad Ice Cream 3",
"Balloon Fight",
"Baseball NES",
"Bejeweled Twist DS",
"Bit Burner",
"Bot WDS",
"Brotato",
"Buck Bumble",
"Cactus McCoy",
"Cactus McCoy 2",
"Carnival Games DS",
"Celeste",
"Celeste 2",
"Celeste Mario DX",
"Celia's Stupid ROM Hack",
"Choroq Wonderful",
"Clu Clu Land",
"Cold Front",
"Cover Orange Players Pack 3",
"Crash 2",
"Crash 3",
"Crash Bandicoot (1)",
"Crash Bash",
"CVOOC",
"Decision 3",
"DK NES Collection",
"Dodeca Dragons",
"Doom Ori",
"Double Dribble",
"Dragon Quest 5 DS",
"Duck Tales 2",
"Dune Dash",
"Dungeons and Degenerate Gambler",
"Dungeons and Degenerate Gambler (Debug)",
"Ecco the Dolphin",
"Elevator Action",
"Escalating Duel",
"EscapeRoad3",
"Eugene'sLife",
"ExciteBike",
"ExitPath",
"FamidashE-Sides1.2.8",
"FantasyZone",
"FinalFantasy2NES",
"FinalFantasy3NES",
"FiveNightsatFrickBears3",
"FloodRunner3",
"FNF-SOHV2",
"F-ZeroX",
"Geometry Dash Wave",
"GettingOverIt",
"GrandShiftAuto",
"Gyromite",
"Hang On SMS",
"Heart and Soul 1.2.1",
"Helltaker",
"HL2 Doom",
"Hoenn's Last Wish",
"Hooked",
"Horn Tale",
"Hungry Lamu 2",
"Hungry Pumpkin",
"Ice Climber",
"I Hate You",
"Impossible Quiz",
"Impossible Quiz 2",
"Jojo Baps 1",
"Just a Platformer",
"Just a Platformer E",
"Just a Platformer E2",
"Knuckles Chaotix",
"Leaf Blower",
"Learn to Fly 2 Hacked",
"Learn to Fly 3 Debug",
"Learn to Fly Idle",
"Learn to Fly Idle Hack",
"Legion Breaker",
"Mach Rider",
"Mario Bros NES",
"Marvel vs Capcom PS1",
"Marvel vs Street Fighter",
"Medal of Honor",
"Mega Man X5",
"Mega Man X6",
"Meow.io",
"Midway's Greatest Hits N64",
"MK Mythologies N64",
"MK Trilogy PS1",
"Mr. Driller",
"Mr. Driller 2",
"Neon Rider",
"Newer SMBS DS",
"New Super Bowser World",
"NG Uidle",
"NSMB U DS",
"NSMB W DS",
"Oot Master Quest",
"Orange Roulette",
"Paper Mario DSE",
"Paper Mario Practice Hack",
"Pinball NES",
"Poke Ambrosia",
"Poke Crystal Advance Redux",
"Poke Crystal Clear",
"Poke Emerald Extended Cut",
"Poke Emerald Imperium",
"Poke Emerald Rogue",
"Poke Emerald Rogue EX",
"Poke FRLG Plus",
"Poke Fusion 3",
"Poke Golden Shield",
"Poke Heartgold Generations",
"Poke Low Budget Crystal",
"Pokemon Emerald Crest",
"Pokemon Emerald Rouge",
"Pokemon Perfect Emerald 5.5",
"Pokemon Stadium 2",
"Pokemon Emerald (2)",
"Pokemon Galaxy",
"Pokemon Picross",
"Pokemon Pure Blue",
"Pokemon Pure Green",
"Pokemon Pure Red",
"Pokemon Rowe",
"Pokemon Scrambled Scarlet",
"Pokemon Sun Sky",
"Poke Theta Emerald EX",
"Pokemon Too Many Types 2",
"Portrait of Ruin",
"Prank Call Tungga Tungga Satur Clicker",
"Prestige Tree",
"Pro Wrestling",
"Punch the Trump",
"Quake",
"clrabbithole106",
"Radical Red",
"React Core",
"Road Runner NES",
"Run from Withered Fox",
"Scooby Doo Creepy Run",
"Scooby Doo Zombie Hunter",
"Sim City 64",
"SINGLEFILE",
"Skywire",
"Skywire 2",
"Slalom NES",
"Slice Master",
"SM64 Green Stars",
"SM64 Land",
"SM64 Last Impact",
"SM64 Liminal Dream",
"SM64 Sapphire",
"SM64 Y Scaled",
"Smash Remix 2.0.1",
"Soccer NES",
"Somari 64",
"Sonic 2 Pink Edition",
"Sonic 2 Time and Place",
"Sonic 3 and Sally",
"Sonic CD",
"Sonic Classic Heroes",
"Sonic Drift",
"Sonic Drift 2",
"Sonic EXE Razor",
"Sonic Mega Mix 5.0a LEAKED",
"Sonic Mushroom Blast",
"Sonic Scorched Quest",
"SOTN",
"Space Harriers SMS",
"Spiderman PS1",
"Sports Heads Ice Hockey",
"Sprunki Pyramixed",
"Star Fox",
"Star Fox 2",
"Star Fox SFX 2",
"Sugary Spire",
"Super Mario 3 Mix",
"Super Mario 74",
"Super Mario Star Road",
"Super Mario Star Road Retooled",
"Swing for Brain Rots",
"Tails Adventure",
"Tails Sky Patrol",
"Tekken 2 PS1",
"Tekken 3 PS1",
"Tennis NES",
"Theme Park PSX",
"The Sun For The Vampire",
"Tomodachi Collection",
"Too Many Types",
"Trees Hate You",
"Tung Tung Basics",
"Um Jammer Lammy",
"Unfair Mario Work Question Mark",
"Urban Champion",
"Uvuvwevwevwe Onyetenvewve Ugwemubwem Ossas",
"VibRibbon",
"Volleyball",
"Wacky Flip",
"WBML",
"Web Dashers",
"Wonder Boy 3",
"Wonder Boy Arcade",
"Wrecking Crew",
"WWF Attitude",
"WWF SmackDown 2",
"XOR",
"codeorg",
"EB.Client.V1.0.0R2.WASM",
"esm",
"npm",
"skypack",
"supremeduelistfix",
"thiefpuzzle",
"unpkg",
"cl?"
];
function generateAllSections() {
  try {
    document.getElementById("lolbutton").remove();
  } catch (e) {}
  const allChars = [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
  ];

   const filesByChar = {};
  allChars.forEach((char) => {
    filesByChar[char] = [];
  });

  files.forEach((file) => {
    const trimmed = file.trim();
    if (trimmed.length > 0) {
      const firstChar = trimmed[0].toUpperCase();
      if (filesByChar[firstChar]) {
        filesByChar[firstChar].push(file);
      }
    }
  });

  const container = document.getElementById("sections-container");
  allChars.forEach((char) => {
    const section = document.createElement("div");
    section.className = "letter-section";
    section.id = `section-${char}`;

    const header = document.createElement("div");
    header.className = "letter-header";
    header.textContent = char;
    section.appendChild(header);

    const buttonsContainer = document.createElement("div");
    buttonsContainer.className = "buttons-container";

    if (filesByChar[char].length > 0) {
      filesByChar[char].forEach((file) => {
        const btn = document.createElement("input");
        btn.type = "button";
        btn.value = file;
        btn.onclick = () => {
          function normalizeFileName(name) {
            if (name.toLowerCase().endsWith(".html")) return name;
            return name + ".html";
          }

          const normalized = normalizeFileName(file);
          const encoded = encodeURIComponent(normalized);

          fetch(
            `https://esm.sh/gh/bitball41/liminal-ugs@main/UGS-Files/${encoded}?t=${Date.now()}`,
          )
            .then((response) => response.text())
            .then((text) => {
              const newWin = window.open("about:blank", "_blank");
              if (newWin) {
                newWin.document.open();
                newWin.document.write(text);
                newWin.document.close();
              }
            });
        };
        btn.style.width = "100%";
        btn.style.height = "100%";
        buttonsContainer.appendChild(btn);
      });
    } else {
      section.classList.add("empty");
      const emptyMsg = document.createElement("div");
      emptyMsg.className = "empty-message";
      emptyMsg.textContent = "No files";
      buttonsContainer.appendChild(emptyMsg);
    }

    section.appendChild(buttonsContainer);
    container.appendChild(section);
  });

  generateSidebar(allChars, filesByChar);
}

function generateSidebar(allChars, filesByChar) {
  const sidebar = document.getElementById("sidebar");

  allChars.forEach((char) => {
    const btn = document.createElement("button");
    btn.className = "sidebar-btn";
    btn.textContent = char;

    if (filesByChar[char].length === 0) {
      btn.classList.add("empty");
    } else {
      btn.onclick = () => {
        const section = document.getElementById(`section-${char}`);
        if (section) {
          section.scrollIntoView({
            behavior: "smooth",
            block: "start",
          });
        }
      };
    }

    sidebar.appendChild(btn);
  });
}
generateAllSections();
